# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-02 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addresss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresss',
            new_name='Address',
        ),
    ]
