# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-03 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200903_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User_profile',
            new_name='user_profile',
        ),
    ]
